CREATE TABLE SERVERTABLE1 (
    FirstName DATETIME,
    LastName DATETIME,
    NickName DATETIME,
);


-- This is a test comment
SELECT
	T1.Field1,
	T1.Field2,
	T1.Field3,
	T1.Field4,
	T1.Field5,
	T1.Field6,
	T1.Field7
INTO ##Table1
FROM SERVERTABLE1 AS T1
JOIN SERVERTABLE2 AS T2
	ON T1.ID = T2.ID
JOIN SERVERTABLE3 AS T3
	ON T2.ID = T3.ID;




SELECT
	T1.Field1,
	T1.Field2,
	T1.Field3,
	T1.Field4,
	T1.Field5,
	T1.Field6,
	T1.Field7
INTO ##Table2
FROM ##Table1 AS T1
JOIN SERVERTABLE5 AS T2
	ON T1.ID = T2.ID
JOIN SERVERTABLE6 AS T3
	ON T2.ID = T3.ID
JOIN SERVERTABLE7 AS T3
	ON T2.ID = T3.ID
JOIN SERVERTABLE8 AS T3
	ON T2.ID = T3.ID;
